/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Bridge.CarneDePollo;
import Bridge.CarneDeRes;
import Bridge.ElaborarAlimento;
import Bridge.ElaborarHamburguesa;
import adapter.Adaptador;
import adapter.IAdaptador;
import com.sun.awt.AWTUtilities;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author aula2
 */
public class adapter extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public adapter() {
        initComponents();
    }
    
    private static String respu;
    
    public static String getRespu() {
        return respu;
    }
    
    public static void setRespu(String respu) {
        adapter.respu = respu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        abstractFactory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        generarAbstract = new javax.swing.JButton();
        pesos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Patrón Adapter");

        resultado.setBackground(new java.awt.Color(46, 46, 46));
        resultado.setColumns(20);
        resultado.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setRows(3);
        resultado.setText("Resultados");
        jScrollPane4.setViewportView(resultado);

        abstractFactory.setBackground(new java.awt.Color(51, 51, 51));
        abstractFactory.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        abstractFactory.setForeground(new java.awt.Color(255, 255, 255));
        abstractFactory.setText("Volver");
        abstractFactory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        abstractFactory.setBorderPainted(false);
        abstractFactory.setContentAreaFilled(false);
        abstractFactory.setFocusPainted(false);
        abstractFactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abstractFactoryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Digita los pesos a convertir");

        generarAbstract.setBackground(new java.awt.Color(0, 0, 0));
        generarAbstract.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        generarAbstract.setForeground(new java.awt.Color(255, 255, 255));
        generarAbstract.setText("Cambiar moneda");
        generarAbstract.setBorderPainted(false);
        generarAbstract.setContentAreaFilled(false);
        generarAbstract.setFocusPainted(false);
        generarAbstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarAbstractActionPerformed(evt);
            }
        });

        pesos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pesos.setText("20000");
        pesos.setToolTipText("Valor");
        pesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pesos)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(abstractFactory, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generarAbstract, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(abstractFactory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(pesos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(generarAbstract, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abstractFactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abstractFactoryActionPerformed
        // TODO add your handling code here:

        formulario abrir = new formulario();
        abrir.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_abstractFactoryActionPerformed

    private void generarAbstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarAbstractActionPerformed
        // TODO add your handling code here:

        DecimalFormat formateador = new DecimalFormat("###,###.##");
        Adaptador conversor = new Adaptador();
        int opci = JOptionPane.YES_OPTION;
        
        Double pesos;
        Double pesosimprimir = 0.0;
        
        pesos = Double.parseDouble(this.pesos.getText());
        pesosimprimir = pesos;
        conversor.ingresarPesos(pesos);
        
        opci = JOptionPane.showConfirmDialog(null, "Desea agregar más pesos?", "agregar",
                JOptionPane.YES_NO_OPTION);
        
        try {
            
            while (opci == JOptionPane.YES_OPTION) {
                pesos = Double.parseDouble(JOptionPane.showInputDialog("Ingrese los pesos adicionales"));
                pesosimprimir += pesos;
                
                conversor.ingresarPesos(pesos);
                opci = JOptionPane.showConfirmDialog(null, "Desea agregar más pesos?", "agregar",
                        JOptionPane.YES_NO_OPTION);
            }
            
        } catch (Exception e) {
            
        }
        
        resultado.setText("Total de dólares: " + formateador.format(conversor.getSaldo()) + "\nPesos ingresados: " + formateador.format(pesosimprimir));
    }//GEN-LAST:event_generarAbstractActionPerformed

    private void pesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abstractFactory;
    private javax.swing.JButton generarAbstract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField pesos;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
