/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import FactoryMethod.Pago;
import FactoryMethod.PagoFactory;
import FactoryMethod.PagoFactoryMethod;

/**
 *
 * @author aula2
 */
public class factorymethod extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public factorymethod() {
        initComponents();
    }

    private static String respu;

    public static String getRespu() {
        return respu;
    }

    public static void setRespu(String respu) {
        factorymethod.respu = respu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        generarMethod = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tipoPago = new javax.swing.JComboBox<>();
        valor1 = new javax.swing.JTextField();
        cliente1 = new javax.swing.JTextField();
        generarMethod1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tipoPago1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        abstractFactory = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        valor2 = new javax.swing.JTextField();
        cliente2 = new javax.swing.JTextField();
        generarMethod2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tipoPago2 = new javax.swing.JComboBox<>();

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione los elementos");

        valor.setText("20000");
        valor.setToolTipText("Valor");

        cliente.setText("Omar Sanchez");
        cliente.setToolTipText("Cliente");

        generarMethod.setBackground(new java.awt.Color(0, 0, 0));
        generarMethod.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        generarMethod.setForeground(new java.awt.Color(255, 255, 255));
        generarMethod.setText("Crear");
        generarMethod.setBorderPainted(false);
        generarMethod.setContentAreaFilled(false);
        generarMethod.setFocusPainted(false);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Seleccione los elementos");

        tipoPago.setBackground(new java.awt.Color(204, 204, 204));
        tipoPago.setForeground(new java.awt.Color(255, 255, 255));
        tipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Transferencia bancaria", "Paypal" }));

        valor1.setText("20000");
        valor1.setToolTipText("Valor");
        valor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1ActionPerformed(evt);
            }
        });

        cliente1.setText("Omar Sanchez");
        cliente1.setToolTipText("Cliente");
        cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente1ActionPerformed(evt);
            }
        });

        generarMethod1.setBackground(new java.awt.Color(0, 0, 0));
        generarMethod1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        generarMethod1.setForeground(new java.awt.Color(255, 255, 255));
        generarMethod1.setText("Crear");
        generarMethod1.setBorderPainted(false);
        generarMethod1.setContentAreaFilled(false);
        generarMethod1.setFocusPainted(false);
        generarMethod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarMethod1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Seleccione los elementos");

        tipoPago1.setBackground(new java.awt.Color(204, 204, 204));
        tipoPago1.setForeground(new java.awt.Color(255, 255, 255));
        tipoPago1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Transferencia bancaria", "Paypal" }));
        tipoPago1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPago1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Patrón F. method");

        abstractFactory.setBackground(new java.awt.Color(51, 51, 51));
        abstractFactory.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        abstractFactory.setForeground(new java.awt.Color(255, 255, 255));
        abstractFactory.setText("Volver");
        abstractFactory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        abstractFactory.setBorderPainted(false);
        abstractFactory.setContentAreaFilled(false);
        abstractFactory.setFocusPainted(false);
        abstractFactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abstractFactoryActionPerformed(evt);
            }
        });

        resultado.setBackground(new java.awt.Color(46, 46, 46));
        resultado.setColumns(20);
        resultado.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setRows(3);
        resultado.setText("Resultados");
        jScrollPane4.setViewportView(resultado);

        valor2.setText("20000");
        valor2.setToolTipText("Valor");
        valor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2ActionPerformed(evt);
            }
        });

        cliente2.setText("Omar Sanchez");
        cliente2.setToolTipText("Cliente");
        cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente2ActionPerformed(evt);
            }
        });

        generarMethod2.setBackground(new java.awt.Color(0, 0, 0));
        generarMethod2.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        generarMethod2.setForeground(new java.awt.Color(255, 255, 255));
        generarMethod2.setText("Crear");
        generarMethod2.setBorderPainted(false);
        generarMethod2.setContentAreaFilled(false);
        generarMethod2.setFocusPainted(false);
        generarMethod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarMethod2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Seleccione los elementos");

        tipoPago2.setBackground(new java.awt.Color(204, 204, 204));
        tipoPago2.setForeground(new java.awt.Color(255, 255, 255));
        tipoPago2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Transferencia bancaria", "Paypal" }));
        tipoPago2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPago2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoPago2, 0, 1, Short.MAX_VALUE)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(abstractFactory, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4)
                            .addComponent(generarMethod2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cliente2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(abstractFactory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoPago2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(cliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generarMethod2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abstractFactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abstractFactoryActionPerformed
        // TODO add your handling code here:

        formulario abrir = new formulario();
        abrir.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_abstractFactoryActionPerformed

    private void valor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor1ActionPerformed

    private void cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente1ActionPerformed

    private void generarMethod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarMethod1ActionPerformed
        // TODO add your handling code here:

        //        resultado.setText(pago.descripcion());
    }//GEN-LAST:event_generarMethod1ActionPerformed

    private void tipoPago1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPago1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPago1ActionPerformed

    private void valor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valor2ActionPerformed

    private void cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente2ActionPerformed

    private void generarMethod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarMethod2ActionPerformed
        // TODO add your handling code here:

        PagoFactoryMethod factory = new PagoFactory();

        Pago pago = factory.generarPago(Integer.parseInt(valor2.getText()), cliente2.getText(), tipoPago2.getSelectedItem().toString());

        System.out.println(pago.descripcion());

        resultado.setText(pago.descripcion());

    }//GEN-LAST:event_generarMethod2ActionPerformed

    private void tipoPago2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPago2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPago2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abstractFactory;
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField cliente1;
    private javax.swing.JTextField cliente2;
    private javax.swing.JButton generarMethod;
    private javax.swing.JButton generarMethod1;
    private javax.swing.JButton generarMethod2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea resultado;
    private javax.swing.JComboBox<String> tipoPago;
    private javax.swing.JComboBox<String> tipoPago1;
    private javax.swing.JComboBox<String> tipoPago2;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField valor1;
    private javax.swing.JTextField valor2;
    // End of variables declaration//GEN-END:variables
}
