/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import AbstractFactory.EnsamblajeTv;
import AbstractFactory.FactoryLDCBlanco;
import AbstractFactory.FactoryLDCNegro;
import AbstractFactory.FactoryPlasmaBlanco;
import AbstractFactory.FactoryPlasmaNegro;
import AbstractFactory.Tv;
import AbstractFactory.TvAbstractFactory;
import FactoryMethod.Pago;
import FactoryMethod.PagoFactory;
import FactoryMethod.PagoFactoryMethod;
import com.sun.awt.AWTUtilities;

/**
 *
 * @author aula2
 */
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();

    }

    private static String respu;

    public static String getRespu() {
        return respu;
    }

    public static void setRespu(String respu) {
        formulario.respu = respu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abstractFactory = new javax.swing.JButton();
        factoryMethod = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        factoryMethod1 = new javax.swing.JButton();
        factoryMethod2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        factoryMethod3 = new javax.swing.JButton();
        factoryMethod4 = new javax.swing.JButton();
        factoryMethod5 = new javax.swing.JButton();
        factoryMethod6 = new javax.swing.JButton();
        factoryMethod7 = new javax.swing.JButton();
        factoryMethod8 = new javax.swing.JButton();
        factoryMethod9 = new javax.swing.JButton();
        factoryMethod10 = new javax.swing.JButton();
        factoryMethod11 = new javax.swing.JButton();
        factoryMethod12 = new javax.swing.JButton();
        factoryMethod13 = new javax.swing.JButton();
        factoryMethod14 = new javax.swing.JButton();
        factoryMethod15 = new javax.swing.JButton();
        factoryMethod16 = new javax.swing.JButton();
        factoryMethod17 = new javax.swing.JButton();
        factoryMethod18 = new javax.swing.JButton();
        factoryMethod19 = new javax.swing.JButton();
        factoryMethod20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patrones de software");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Elkin Jiménez - Omar Sanchez");

        abstractFactory.setBackground(new java.awt.Color(0, 0, 0));
        abstractFactory.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        abstractFactory.setForeground(new java.awt.Color(255, 255, 255));
        abstractFactory.setText("Abstract Factory");
        abstractFactory.setBorderPainted(false);
        abstractFactory.setContentAreaFilled(false);
        abstractFactory.setFocusPainted(false);
        abstractFactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abstractFactoryActionPerformed(evt);
            }
        });

        factoryMethod.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod.setText(" Factory Method ");
        factoryMethod.setBorderPainted(false);
        factoryMethod.setContentAreaFilled(false);
        factoryMethod.setFocusPainted(false);
        factoryMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethodActionPerformed(evt);
            }
        });

        factoryMethod1.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod1.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod1.setText("Bridge");
        factoryMethod1.setBorderPainted(false);
        factoryMethod1.setContentAreaFilled(false);
        factoryMethod1.setFocusPainted(false);
        factoryMethod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod1ActionPerformed(evt);
            }
        });

        factoryMethod2.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod2.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod2.setText("Adapter");
        factoryMethod2.setBorderPainted(false);
        factoryMethod2.setContentAreaFilled(false);
        factoryMethod2.setFocusPainted(false);
        factoryMethod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("De creación");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estructurales");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("De comportamiento");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Seleccione uno");

        factoryMethod3.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod3.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod3.setText("Iterator");
        factoryMethod3.setBorderPainted(false);
        factoryMethod3.setContentAreaFilled(false);
        factoryMethod3.setFocusPainted(false);
        factoryMethod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod3ActionPerformed(evt);
            }
        });

        factoryMethod4.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod4.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod4.setText("Memento");
        factoryMethod4.setBorderPainted(false);
        factoryMethod4.setContentAreaFilled(false);
        factoryMethod4.setFocusPainted(false);
        factoryMethod4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod4ActionPerformed(evt);
            }
        });

        factoryMethod5.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod5.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod5.setText("Command");
        factoryMethod5.setBorderPainted(false);
        factoryMethod5.setContentAreaFilled(false);
        factoryMethod5.setEnabled(false);
        factoryMethod5.setFocusPainted(false);
        factoryMethod5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod5ActionPerformed(evt);
            }
        });

        factoryMethod6.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod6.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod6.setText("Mediator");
        factoryMethod6.setBorderPainted(false);
        factoryMethod6.setContentAreaFilled(false);
        factoryMethod6.setFocusPainted(false);
        factoryMethod6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod6ActionPerformed(evt);
            }
        });

        factoryMethod7.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod7.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod7.setText("Observer");
        factoryMethod7.setBorderPainted(false);
        factoryMethod7.setContentAreaFilled(false);
        factoryMethod7.setFocusPainted(false);
        factoryMethod7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod7ActionPerformed(evt);
            }
        });

        factoryMethod8.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod8.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod8.setText("State");
        factoryMethod8.setBorderPainted(false);
        factoryMethod8.setContentAreaFilled(false);
        factoryMethod8.setFocusPainted(false);
        factoryMethod8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod8ActionPerformed(evt);
            }
        });

        factoryMethod9.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod9.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod9.setText("Strategy");
        factoryMethod9.setBorderPainted(false);
        factoryMethod9.setContentAreaFilled(false);
        factoryMethod9.setFocusPainted(false);
        factoryMethod9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod9ActionPerformed(evt);
            }
        });

        factoryMethod10.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod10.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod10.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod10.setText("Template Method");
        factoryMethod10.setBorderPainted(false);
        factoryMethod10.setContentAreaFilled(false);
        factoryMethod10.setFocusPainted(false);
        factoryMethod10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod10ActionPerformed(evt);
            }
        });

        factoryMethod11.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod11.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod11.setText("Visitor");
        factoryMethod11.setBorderPainted(false);
        factoryMethod11.setContentAreaFilled(false);
        factoryMethod11.setFocusPainted(false);
        factoryMethod11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod11ActionPerformed(evt);
            }
        });

        factoryMethod12.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod12.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod12.setText("Chain of Responsability");
        factoryMethod12.setBorderPainted(false);
        factoryMethod12.setContentAreaFilled(false);
        factoryMethod12.setFocusPainted(false);
        factoryMethod12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod12ActionPerformed(evt);
            }
        });

        factoryMethod13.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod13.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod13.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod13.setText("Composite");
        factoryMethod13.setBorderPainted(false);
        factoryMethod13.setContentAreaFilled(false);
        factoryMethod13.setFocusPainted(false);
        factoryMethod13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod13ActionPerformed(evt);
            }
        });

        factoryMethod14.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod14.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod14.setText("Decorator");
        factoryMethod14.setBorderPainted(false);
        factoryMethod14.setContentAreaFilled(false);
        factoryMethod14.setFocusPainted(false);
        factoryMethod14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod14ActionPerformed(evt);
            }
        });

        factoryMethod15.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod15.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod15.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod15.setText("Facade");
        factoryMethod15.setBorderPainted(false);
        factoryMethod15.setContentAreaFilled(false);
        factoryMethod15.setFocusPainted(false);
        factoryMethod15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod15ActionPerformed(evt);
            }
        });

        factoryMethod16.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod16.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod16.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod16.setText("Flyweight");
        factoryMethod16.setBorderPainted(false);
        factoryMethod16.setContentAreaFilled(false);
        factoryMethod16.setFocusPainted(false);
        factoryMethod16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod16ActionPerformed(evt);
            }
        });

        factoryMethod17.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod17.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod17.setText("Proxy");
        factoryMethod17.setBorderPainted(false);
        factoryMethod17.setContentAreaFilled(false);
        factoryMethod17.setFocusPainted(false);
        factoryMethod17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod17ActionPerformed(evt);
            }
        });

        factoryMethod18.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod18.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod18.setText("Builder");
        factoryMethod18.setBorderPainted(false);
        factoryMethod18.setContentAreaFilled(false);
        factoryMethod18.setFocusPainted(false);
        factoryMethod18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod18ActionPerformed(evt);
            }
        });

        factoryMethod19.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod19.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod19.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod19.setText("Prototype");
        factoryMethod19.setBorderPainted(false);
        factoryMethod19.setContentAreaFilled(false);
        factoryMethod19.setFocusPainted(false);
        factoryMethod19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod19ActionPerformed(evt);
            }
        });

        factoryMethod20.setBackground(new java.awt.Color(0, 0, 0));
        factoryMethod20.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        factoryMethod20.setForeground(new java.awt.Color(255, 255, 255));
        factoryMethod20.setText("Singleton");
        factoryMethod20.setBorderPainted(false);
        factoryMethod20.setContentAreaFilled(false);
        factoryMethod20.setFocusPainted(false);
        factoryMethod20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factoryMethod20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(abstractFactory)
                                    .addComponent(factoryMethod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(factoryMethod18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(factoryMethod19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(factoryMethod20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(factoryMethod13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(factoryMethod1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(factoryMethod2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(factoryMethod14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(factoryMethod4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod7, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(factoryMethod9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(factoryMethod10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(factoryMethod12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod11, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(factoryMethod3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(abstractFactory, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(factoryMethod1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factoryMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factoryMethod5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factoryMethod6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factoryMethod7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factoryMethod8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factoryMethod9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factoryMethod17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(factoryMethod10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(factoryMethod11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(factoryMethod12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void factoryMethod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod2ActionPerformed
        // TODO add your handling code here:

        adapter abrir = new adapter();
        abrir.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_factoryMethod2ActionPerformed

    private void factoryMethod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod1ActionPerformed
        // TODO add your handling code here:

        bridge abrir = new bridge();
        abrir.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_factoryMethod1ActionPerformed

    private void factoryMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethodActionPerformed
        // TODO add your handling code here:

        factorymethod abrir = new factorymethod();
        abrir.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_factoryMethodActionPerformed

    private void abstractFactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abstractFactoryActionPerformed
        // TODO add your handling code here:

        abstractfactory abrir = new abstractfactory();
        abrir.setVisible(true);

        this.setVisible(false);

    }//GEN-LAST:event_abstractFactoryActionPerformed

    private void factoryMethod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod3ActionPerformed
        // TODO add your handling code here:

        iterator abrir = new iterator();
        abrir.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_factoryMethod3ActionPerformed

    private void factoryMethod4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod4ActionPerformed
        // TODO add your handling code here:

        memento abrir = new memento();
        abrir.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_factoryMethod4ActionPerformed

    private void factoryMethod5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod5ActionPerformed

    private void factoryMethod6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod6ActionPerformed

    private void factoryMethod7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod7ActionPerformed

    private void factoryMethod8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod8ActionPerformed

    private void factoryMethod9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod9ActionPerformed

    private void factoryMethod10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod10ActionPerformed

    private void factoryMethod11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod11ActionPerformed

    private void factoryMethod12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod12ActionPerformed

    private void factoryMethod13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod13ActionPerformed

    private void factoryMethod14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod14ActionPerformed

    private void factoryMethod15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod15ActionPerformed

    private void factoryMethod16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod16ActionPerformed

    private void factoryMethod17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod17ActionPerformed

    private void factoryMethod18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod18ActionPerformed

    private void factoryMethod19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod19ActionPerformed

    private void factoryMethod20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factoryMethod20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factoryMethod20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abstractFactory;
    private javax.swing.JButton factoryMethod;
    private javax.swing.JButton factoryMethod1;
    private javax.swing.JButton factoryMethod10;
    private javax.swing.JButton factoryMethod11;
    private javax.swing.JButton factoryMethod12;
    private javax.swing.JButton factoryMethod13;
    private javax.swing.JButton factoryMethod14;
    private javax.swing.JButton factoryMethod15;
    private javax.swing.JButton factoryMethod16;
    private javax.swing.JButton factoryMethod17;
    private javax.swing.JButton factoryMethod18;
    private javax.swing.JButton factoryMethod19;
    private javax.swing.JButton factoryMethod2;
    private javax.swing.JButton factoryMethod20;
    private javax.swing.JButton factoryMethod3;
    private javax.swing.JButton factoryMethod4;
    private javax.swing.JButton factoryMethod5;
    private javax.swing.JButton factoryMethod6;
    private javax.swing.JButton factoryMethod7;
    private javax.swing.JButton factoryMethod8;
    private javax.swing.JButton factoryMethod9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
