/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Memento.Memento;
import Memento.Usuario;
import Memento.Vigilante;

/**
 *
 * @author aula2
 */
public class memento extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public memento() {
        initComponents();
    }

    Vigilante vigilante = new Vigilante();

    Usuario u = new Usuario();

    private static String respu;

    public static String getRespu() {
        return respu;
    }

    public static void setRespu(String respu) {
        memento.respu = respu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        abstractFactory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        generarAbstract = new javax.swing.JButton();
        nombreUsuario = new javax.swing.JTextField();
        GuardarCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 33, 33));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Patrón Memento");

        resultado.setBackground(new java.awt.Color(46, 46, 46));
        resultado.setColumns(20);
        resultado.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        resultado.setForeground(new java.awt.Color(255, 255, 255));
        resultado.setRows(3);
        resultado.setText("Resultados");
        jScrollPane4.setViewportView(resultado);

        abstractFactory.setBackground(new java.awt.Color(51, 51, 51));
        abstractFactory.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        abstractFactory.setForeground(new java.awt.Color(255, 255, 255));
        abstractFactory.setText("Volver");
        abstractFactory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        abstractFactory.setBorderPainted(false);
        abstractFactory.setContentAreaFilled(false);
        abstractFactory.setFocusPainted(false);
        abstractFactory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abstractFactoryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Digite el nombre del usuario");

        generarAbstract.setBackground(new java.awt.Color(0, 0, 0));
        generarAbstract.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        generarAbstract.setForeground(new java.awt.Color(255, 255, 255));
        generarAbstract.setText("Enviar");
        generarAbstract.setBorderPainted(false);
        generarAbstract.setContentAreaFilled(false);
        generarAbstract.setFocusPainted(false);
        generarAbstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarAbstractActionPerformed(evt);
            }
        });

        nombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nombreUsuario.setText("Omar Sanchez");
        nombreUsuario.setToolTipText("Valor");
        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });

        GuardarCheck.setBackground(new java.awt.Color(255, 255, 255));
        GuardarCheck.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GuardarCheck.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCheck.setSelected(true);
        GuardarCheck.setText("  Guardar");
        GuardarCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(abstractFactory, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(generarAbstract, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(nombreUsuario, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(GuardarCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(abstractFactory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GuardarCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addComponent(generarAbstract, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abstractFactoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abstractFactoryActionPerformed
        // TODO add your handling code here:

        formulario abrir = new formulario();
        abrir.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_abstractFactoryActionPerformed

    private void generarAbstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarAbstractActionPerformed
        // TODO add your handling code here:

        respu = "NO SE GUARDÓ: " + nombreUsuario.getText() + "\n______________________________";

        u.setNombre(nombreUsuario.getText());

        if (GuardarCheck.isSelected()) {

            vigilante.agregarMemento(u.GuardarAMenento());

        }

        for (int i = 0; i < vigilante.getEstados().size(); i++) {

            Memento m = vigilante.getMemento(i);
            respu += "\n" + m.getGuardarEstado();
            System.out.println(m.getGuardarEstado());

        }

        resultado.setText(respu);
    }//GEN-LAST:event_generarAbstractActionPerformed

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioActionPerformed

    private void GuardarCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCheckActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_GuardarCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox GuardarCheck;
    private javax.swing.JButton abstractFactory;
    private javax.swing.JButton generarAbstract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
